export const environment = {
  production: false,
  supabaseUrl: 'https://hjypgegmbqejiihdznhv.supabase.co',
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeXBnZWdtYnFlamlpaGR6bmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTQ2OTgsImV4cCI6MjA2MDg5MDY5OH0.YWKzPD4wgNWk4tGivWutRy7qNalAU0IoQIYgwM56n1QeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeXBnZWdtYnFlamlpaGR6bmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTQ2OTgsImV4cCI6MjA2MDg5MDY5OH0.YWKzPD4wgNWk4tGivWutRy7qNalAU0IoQIYgwM56n1Q'
};